import { Metadata } from "next"
import QuizContainer from "../components/Quiz/Quiz"

export const metadata: Metadata = {
  title: 'Quiz Page',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
      <QuizContainer />
    )
  }
